### ISSUE TITLE
Добавить в проект .gitignore и исключить директорию venv 

### ISSUE THREAD

**Issue by ProSerg** [TatianaVR/DjangoTest#1]
В репозиториях не хранят генерируемые файлы в том числе и файлы виртуального окружения.
Рекомендую разобраться с gitignore и удалить из репозитория директорию venv.

https://git-scm.com/docs/gitignore

**Comment by TatianaVR** [comment]
Сергей, попробую сделать, но позже. сейчас интереснее создать сайт полностью.
