### ISSUE TITLE
Delete folder from repository

### ISSUE THREAD

**Issue by TatianaVR** [TatianaVR/DjangoTest#3]
Sequence of actions to remove from the repository

Delete:
C:\Users\W10\PycharmProjects\DjangoTest>git rm -r --cached venv

Create commit:
C:\Users\W10\PycharmProjects\DjangoTest>git commit  -m "Delete venv"

Publish changes to a branch:
C:\Users\W10\PycharmProjects\DjangoTest>git push origin master

**Comment by ProSerg** [comment]
you can close this task.
